### PR TITLE
Fixed: #123 gallery display & add copyright disable option

### PR DESCRIPTION
**Pull request by upupming**
#123 

# Test example

```md
---
title: Gallery
type: "gallery"
copyright:
  disable: true
---

## Title 1

这是相册的第一部分

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}

## Title 2

这是相册的第二部分

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}

## Title 3

这是相册的第三部分

{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
```

# Test result

fireshot capture 11 - gallery i upupming - http___localhost_4000_2018_07_22_test_ title-2

**Remember to disable the copyright notice!**

### CODE REVIEW

**Comment by Molunerfinn** [comment]
I have fixed this problem. Thanks all the same!

**Comment by upupming** [comment]
But it seems the image size should not be changed. 

I have tested your fixed version, here is the result:

screenshot from 2018-07-22 23-26-52

So I deleted the 
```styl
@media screen and (max-width: $sm)
    ...
```
in this pull request

What do you think?

**Comment by Molunerfinn** [comment]
It's for display better in mobile. Your test width isn't an usually width which user will see.

**Comment by upupming** [comment]
This is in ipad:
screenshot from 2018-07-22 23-45-39

**Comment by Molunerfinn** [comment]
I know. It width is `768px`. And I think it's OK because I didn't say it should be a square.

**Comment by Molunerfinn** [comment]
You should know most of the pictures' size is `16:9` so in this case,  I think the situation is in reason. We can't hold all the situation, but we should cover the most situation which people will see the blog in PC or mobile & they will see the `gallery` page in a very few times.

**Comment by upupming** [comment]
Well, thanks for your explanation!

**Pull request closed without merging**
